# Generated by Django 5.1.1 on 2024-10-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='codeforces_handle',
            field=models.CharField(max_length=100),
        ),
    ]
