# Generated by Django 5.1.1 on 2024-10-18 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('contest_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('number_of_problems', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='api.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='api.userprofile')),
            ],
            options={
                'unique_together': {('contest_id', 'from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member1', to='api.userprofile')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member2', to='api.userprofile')),
                ('user3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member3', to='api.userprofile')),
            ],
            options={
                'unique_together': {('team_name', 'contest_id')},
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=255)),
                ('problem_link', models.URLField()),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests')),
            ],
            options={
                'unique_together': {('contest_id', 'problem_name')},
            },
        ),
    ]
