# Generated by Django 5.1.1 on 2024-10-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contests_invites_participants_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='max_rating',
            field=models.IntegerField(default=3500),
        ),
        migrations.AddField(
            model_name='contests',
            name='min_rating',
            field=models.IntegerField(default=800),
        ),
    ]
