# Generated by Django 5.1.1 on 2024-10-18 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contests_max_rating_contests_min_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
