# Generated by Django 5.1.1 on 2024-10-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_contests_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
