# Generated by Django 5.1.1 on 2024-10-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_contests_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invites',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='problems',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.AlterUniqueTogether(
            name='invites',
            unique_together={('contest', 'from_user', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together={('team_name', 'contest')},
        ),
        migrations.AlterUniqueTogether(
            name='problems',
            unique_together={('contest', 'problem_name')},
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField(default=0)),
                ('solve_count', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants')),
            ],
            options={
                'unique_together': {('contest', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_attempted', models.CharField(max_length=255)),
                ('is_it_solved', models.BooleanField(default=False)),
                ('time_of_solve', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contests')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participants')),
            ],
            options={
                'unique_together': {('contest', 'team', 'problem_attempted')},
            },
        ),
    ]
