# Generated by Django 5.1.1 on 2024-10-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_contest_id_invites_contest_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participants',
            unique_together={('user1', 'contest')},
        ),
    ]
