# Generated by Django 5.1.1 on 2024-10-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_contests_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='for_team',
            field=models.BooleanField(default=False),
        ),
    ]
